<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <DefineConstants>NICEIO_PUBLIC</DefineConstants>
    <Nullable>disable</Nullable> <!-- not ready for this yet -->
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="NiceIO.Tests/**" />
  </ItemGroup>
</Project>
