name: Validate Dev Branch

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  validate:
    name: Validate ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      - name: Run regular tests
        run: |
          dotnet test --nologo -l:"console;verbosity=normal"

      - name: Run package tests
        if: matrix.os == 'windows-latest' # TODO: getting bizarre CS1012 errors on unix
        run: |
          cd NiceIO.PackageTest
          dotnet pack .. -p:NuspecFile=NiceIO.nuspec -c Release
          dotnet add package OkTools.NiceIO --source ../bin/Release --package-directory packages
          dotnet run
